# DataMonitor Pro

**DataMonitor Pro** — это приложение для мониторинга и анализа данных в реальном времени. Оно принимает данные по сети, отображает их в таблице, сохраняет историю в базу данных и позволяет экспортировать результаты.

---

##   Возможности

-  **Прием данных** — TCP/WebSocket сервер для приема данных в формате JSON
-  **Визуализация** — график реального времени и таблица с данными
-  **Сохранение истории** — все данные сохраняются в SQLite
-  **Фильтрация** — по типу данных и временному диапазону
-  **Статистика** — расчет минимума, максимума, среднего
-  **Экспорт** — сохранение данных в CSV и PDF

---

## Технологии

| Технология | Версия | Назначение |
|------------|--------|------------|
| C++ | 20 | Основной язык программирования |
| Qt | 6.10 | Фреймворк для GUI и сетевого взаимодействия |
| QML | 6 | Современный интерфейс |
| SQLite | 3 | Встраиваемая база данных |
| PostgreSQL(основная субд) |
| CMake | 3.20+ | Система сборки |

---

  Установка и сборка

Требования

- Qt 6.10 или выше (с компонентом MinGW 64-bit)
- CMake 3.20 или выше
- Git (опционально)

Сборка проекта

```bash
# Клонирование репозитория
git clone https://github.com/yourusername/DataMonitorPro.git
cd DataMonitorPro

# Создание папки для сборки
mkdir build
cd build

# Конфигурация CMake
cmake ..

# Компиляция
cmake --build . --config Release

Тестирование:

#Локальная отправка данных (на том же компьютере)
1. Запустите DataMonitor Pro, нажмите *Start Server*
2. Откройте в браузере файл //tools/websocket_sender.html//
3. Нажмите *Connect*, затем *Отправить*
4. Данные появятся в таблице приложения


Удаленная отправка данных (с другого компьютера)
1. На сервере запустите DataMonitor Pro, нажмите *Start Server*
2. Узнайте IP-адрес сервера командой //ipconfig//
3. На другом компьютере откройте //tools/websocket_client.html//
4. Введите IP-адрес сервера, нажмите *Connect*
5. Отправляйте данные — они появятся на сервере


# В папке docs/screenshots "2 скрина рабочей области отправки данных."